### ISSUE TITLE
400 MESSAGE_NOT_MODIFIED

### ISSUE THREAD

**Issue by KSKOP69** [Pranav-Saraswat/YukkiMusicFork#34]
```
2024-02-09T14:18:33.419347+00:00 app[worker.1]: [09-Feb-24 14:18:33 - ERROR] - pyrogram.dispatcher - Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
2024-02-09T14:18:33.419373+00:00 app[worker.1]: Traceback (most recent call last):
2024-02-09T14:18:33.419374+00:00 app[worker.1]:   File "/opt/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2024-02-09T14:18:33.419374+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2024-02-09T14:18:33.419375+00:00 app[worker.1]:   File "/app/YukkiMusic/utils/decorators/language.py", line 44, in wrapper
2024-02-09T14:18:33.419375+00:00 app[worker.1]:     return await mystic(_, CallbackQuery, language)
2024-02-09T14:18:33.419375+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-09T14:18:33.419376+00:00 app[worker.1]:   File "/app/YukkiMusic/plugins/play/play.py", line 720, in slider_queries
2024-02-09T14:18:33.419376+00:00 app[worker.1]:     return await CallbackQuery.edit_message_media(
2024-02-09T14:18:33.419376+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-09T14:18:33.419378+00:00 app[worker.1]:   File "/opt/venv/lib/python3.11/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 271, in edit_message_media
2024-02-09T14:18:33.419379+00:00 app[worker.1]:     return await self._client.edit_message_media(
2024-02-09T14:18:33.419379+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-09T14:18:33.419379+00:00 app[worker.1]:   File "/opt/venv/lib/python3.11/site-packages/pyrogram/methods/messages/edit_message_media.py", line 271, in edit_message_media
2024-02-09T14:18:33.419380+00:00 app[worker.1]:     r = await self.invoke(
2024-02-09T14:18:33.419380+00:00 app[worker.1]:         ^^^^^^^^^^^^^^^^^^
2024-02-09T14:18:33.419380+00:00 app[worker.1]:   File "/opt/venv/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
2024-02-09T14:18:33.419380+00:00 app[worker.1]:     r = await self.session.invoke(
2024-02-09T14:18:33.419380+00:00 app[worker.1]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-09T14:18:33.419380+00:00 app[worker.1]:   File "/opt/venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
2024-02-09T14:18:33.419381+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
2024-02-09T14:18:33.419381+00:00 app[worker.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-09T14:18:33.419381+00:00 app[worker.1]:   File "/opt/venv/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
2024-02-09T14:18:33.419381+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2024-02-09T14:18:33.419382+00:00 app[worker.1]:   File "/opt/venv/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2024-02-09T14:18:33.419382+00:00 app[worker.1]:     raise getattr(
2024-02-09T14:18:33.419382+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
```

**Comment by Pranav-Saraswat** [comment]
It's a telegram server side problem
