### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KSKOP69** [Pranav-Saraswat/YukkiMusicFork#38]
```
[28-Feb-24 07:39:48 - ERROR] - pyrogram.methods.advanced.save_file - Request timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
    await session.invoke(data)
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 402, in invoke
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 351, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out
[28-Feb-24 07:42:34 - ERROR] - pyrogram.dispatcher - Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.SendMedia")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/app/YukkiMusic/utils/decorators/play.py", line 187, in wrapper
    return await command(
           ^^^^^^^^^^^^^^
  File "/app/YukkiMusic/plugins/play/play.py", line 462, in play_commnd
    await message.reply_photo(
  File "/usr/local/lib/python3.11/site-packages/pyrogram/types/messages_and_media/message.py", line 2087, in reply_photo
    return await self._client.send_photo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/messages/send_photo.py", line 192, in send_photo
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonDataInvalid: Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.SendMedia")
[28-Feb-24 08:00:28 - ERROR] - pyrogram.methods.advanced.save_file - Request timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
    await session.invoke(data)
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 402, in invoke
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 351, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out
[28-Feb-24 08:04:27 - ERROR] - pyrogram.methods.advanced.save_file - Request timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
    await session.invoke(data)
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 402, in invoke
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 351, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out
[28-Feb-24 08:07:19 - ERROR] - pyrogram.methods.advanced.save_file - Request timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/advanced/save_file.py", line 109, in worker
    await session.invoke(data)
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 402, in invoke
    raise e from None
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/session.py", line 351, in send
    raise TimeoutError("Request timed out")
TimeoutError: Request timed out

```

**Comment by zeiyo** [comment]
Try using python version 3.9 or 3.10 I managed to run with that version, but there was an error like yesterday 
```
Some exception occured while processing your query.

Exception Type:- ChannelInvalid
```

**Comment by Pranav-Saraswat** [comment]
@annihilatorrrr hey spark can you please look into this I have my exam so currently I don't have to fix this at a moment

**Comment by KSKOP69** [comment]
```
[02-Mar-24 12:39:49 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-705876' coro=<Call.decorators.<locals>.stream_end_handler() done, defined at /app/YukkiMusic/core/call.py:571> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/app/YukkiMusic/core/call.py", line 579, in stream_end_handler
    await self.change_stream(client, update.chat_id)
  File "/app/YukkiMusic/core/call.py", line 521, in change_stream
    db[chat_id][0]["mystic"] = run
    ~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by KSKOP69** [comment]
Fixed
